FoxyBurrow/Models/FriendsViewModel.cs
using FoxyBurrow.Core.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FoxyBurrow.Models
{
    public class FriendsViewModel
    {
        public ICollection<User> Users;
    }
}

FoxyBurrow/Models/SearchFriendsViewModel.cs
using FoxyBurrow.Core.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FoxyBurrow.Models
{
    public class SearchFriendsViewModel
    {
        public ICollection<User> Users { get; set; }
        public string Request { get; set; }
    }
}

FoxyBurrow/Controllers/RequestController.cs
using FoxyBurrow.Core.Entity;
using FoxyBurrow.Models;
using FoxyBurrow.Service.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FoxyBurrow.Controllers
{
    public class RequestController : Controller
    {
        private readonly IUserService _userService;
        private readonly IRequestService _requestService;
        private readonly ILogger<HomeController> _logger;
        public RequestController(IUserService userService, IRequestService requestService,
            ILogger<HomeController> logger)
        {
            _userService = userService;
            _requestService = requestService;
            _logger = logger;
        }
        public async Task<IActionResult> Friends()
        {
            User user = await _userService.GetAsync(User);
            var model = new FriendsViewModel
            {
                Users = _userService.GetFriends(user)
            };
            return View(model);
        }
        public async Task<IActionResult> Followers()
        {
            User user = await _userService.GetAsync(User);
            var model = new FriendsViewModel
            {
                Users = _userService.GetFollowers(user)
            };
            return View(model);
        }
        public async Task<IActionResult> Following()
        {
            User user = await _userService.GetAsync(User);
            var model = new FriendsViewModel
            {
                Users = _userService.GetFollowing(user)
            };
            return View(model);
        }
        public async Task<IActionResult> AddFriend(string id)
        {
            User curUser = await _userService.GetAsync(User);
            User friend = await _userService.GetAsync(id);
            _requestService.AddFriend(curUser, friend);
            return RedirectToAction("Index","Profile", new { id } );
        }
        public async Task<IActionResult> DeleteFriend(string id)
        {
            User curUser = await _userService.GetAsync(User);
            User friend = await _userService.GetAsync(id);
            _requestService.DeleteFriend(curUser, friend);
            return RedirectToAction("Index", "Profile", new { id });
        }

        [HttpGet]
        public async Task<IActionResult> SearchFriends(string request)
        {
            var model = new SearchFriendsViewModel
            {
                Users = (await _userService.FindOtherUsers(User, request)).ToList(),
                Request = request,
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> SearchFriends(SearchFriendsViewModel model)
        {
            model.Users = (await _userService.FindOtherUsers(User, model?.Request)).ToList();
            return View(model);
        }
    }
}

FoxyBurrow/ViewComponents/FriendListViewComponent.cs
using FoxyBurrow.Core.Entity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FoxyBurrow.ViewComponents
{
    public class FriendListViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(ICollection<User> model)
        {
            return View(model);
        }
    }
}

FoxyBurrow/Views/Request/Followers.cshtml
@model FriendsViewModel
@{
    ViewData["Title"] = "Followers";
}
<div class="text-center" style="width:500px; margin-left: auto;margin-right: auto;">
    <div class="text-light bg-dark border-block-rounded d-flex justify-content-center mb-1 p-1">
        <h2 style="color: #F0D745;"> Followers (Incoming requests) </h2>
    </div>
    <vc:friend-list model=@Model.Users></vc:friend-list>
</div>

FoxyBurrow/Views/Request/Following.cshtml
@model FriendsViewModel 
@{
    ViewData["Title"] = "Following";
}
<div class="text-center" style="width:500px; margin-left: auto;margin-right: auto;">
    <div class="text-light bg-dark border-block-rounded d-flex justify-content-center mb-1 p-1">
        <h2 style="color: #F0D745;"> Following (Outgoing requests) </h2>
    </div>
    <vc:friend-list model=@Model.Users></vc:friend-list>
</div>

FoxyBurrow/Views/Request/Friends.cshtml
@model FriendsViewModel
@{
    ViewData["Title"] = "Friends";
}
<div class="text-center" style="width:500px; margin-left: auto;margin-right: auto;">
    <div class="text-light bg-dark border-block-rounded d-flex justify-content-center mb-1 p-1">
        <h2 style="color: #F0D745;"> Friends </h2>
    </div>
    <vc:friend-list model=@Model.Users></vc:friend-list>
</div>

FoxyBurrow/Views/Request/SearchFriends.cshtml
@model SearchFriendsViewModel
@inject IImageService imageService
@{
    ViewData["Title"] = "Search Friends";
}
<div class="text-center" style="width:600px; margin-left: auto;margin-right: auto;">
    <div class="user-search-request">
        <form asp-action="SearchFriends" asp-controller="Request" class="row mt-3 mb-1" method="post">
            <input asp-for="Request" class="form-control col-sm-9" placeholder="Write name or/and surname" />
            <button class="btn btn-primary col-sm-3" type="submit"> Search</button>
        </form>
    </div>
    @if (Model.Users.Count == 0)
    {
        <h1 class="text-danger"> Not Found</h1>
    }
    else
    {
        <div class="user-search-result">
            <vc:friend-list model=@Model.Users></vc:friend-list>
        </div>
    }
</div>