FoxyBurrow/Controllers/ChatController.cs
using FoxyBurrow.Core.Entity;
using FoxyBurrow.Service.Interface;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FoxyBurrow.Controllers
{
    public class ChatController : Controller
    {
        private readonly IUserService _userService;
        private readonly IChatService _chatService;
        private readonly IMessageService _messageService;
        public ChatController(IUserService userService, IChatService chatService, IMessageService messageService)
        {
            _userService = userService;
            _chatService = chatService;
            _messageService = messageService;
        }
        public async Task<IActionResult> Index(string userId)
        {
            User curUser = await _userService.GetAsync(User);
            User friend = await _userService.GetAsync(userId);
            Chat chat = _chatService.GetOrCreate(curUser, friend);
            return View(chat);
        }
        public async Task<IActionResult> List()
        {
            User user = await _userService.GetAsync(User);
            List<Chat> chatList = _chatService.GetAll(user).ToList();
            return View(chatList);      
        }
        public async  Task<IActionResult> Delete(long chatId)
        {
            User curUser = await _userService.GetAsync(User);
            Chat chat = _chatService.Get(chatId);
            if(chat.FirstUserId == curUser.Id || chat.SecondUserId == curUser.Id)
            {
                _chatService.Remove(chatId);
            }
            return RedirectToAction("List");
        }
    }
}

FoxyBurrow/Controllers/RequestController.cs
using FoxyBurrow.Core.Entity;
using FoxyBurrow.Models;
using FoxyBurrow.Service.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FoxyBurrow.Controllers
{
    public class RequestController : Controller
    {
        private readonly IUserService _userService;
        private readonly IRequestService _requestService;
        private readonly ILogger<HomeController> _logger;
        public RequestController(IUserService userService, IRequestService requestService,
            ILogger<HomeController> logger)
        {
            _userService = userService;
            _requestService = requestService;
            _logger = logger;
        }
        public async Task<IActionResult> Friends()
        {
            User user = await _userService.GetAsync(User);
            var model = new FriendsViewModel
            {
                Users = _userService.GetFriends(user)
            };
            return View(model);
        }
        public async Task<IActionResult> Followers()
        {
            User user = await _userService.GetAsync(User);
            var model = new FriendsViewModel
            {
                Users = _userService.GetFollowers(user)
            };
            return View(model);
        }
        public async Task<IActionResult> Following()
        {
            User user = await _userService.GetAsync(User);
            var model = new FriendsViewModel
            {
                Users = _userService.GetFollowing(user)
            };
            return View(model);
        }
        public async Task<IActionResult> AddFriend(string id)
        {
            User curUser = await _userService.GetAsync(User);
            User friend = await _userService.GetAsync(id);
            _requestService.AddFriend(curUser, friend);
            return RedirectToAction("Index","Profile", new { id } );
        }
        public async Task<IActionResult> DeleteFriend(string id)
        {
            User curUser = await _userService.GetAsync(User);
            User friend = await _userService.GetAsync(id);
            _requestService.DeleteFriend(curUser, friend);
            return RedirectToAction("Index", "Profile", new { id });
        }

        [HttpGet]
        public async Task<IActionResult> SearchFriends(string request)
        {
            var model = new SearchFriendsViewModel
            {
                Users = (await _userService.FindOtherUsers(User, request)).ToList(),
                Request = request,
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> SearchFriends(SearchFriendsViewModel model)
        {
            model.Users = (await _userService.FindOtherUsers(User, model?.Request)).ToList();
            return View(model);
        }
    }
}

FoxyBurrow/Views/Shared/_Layout.cshtml
@inject SignInManager<User> signInManager
@inject UserManager<User> userManager
@inject IImageService imageService 
@{ 
    User user = await userManager.GetUserAsync(User);
    string imagePath = imageService.getUserImagePath(user);
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]  FoxyBurrow</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/chat.css" />
    <link rel="stylesheet" href="~/css/comment.css" />
    <link rel="stylesheet" href="~/css/post.css" />
    <link rel="stylesheet" href="~/css/profile.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="@Url.Content("~/img/logo/Logo.ico")" class="logo-image rounded-circle" />
                </a>
                <a class="navbar-nav" id="logo-title" asp-area="" asp-controller="Home" asp-action="Index">
                    FoxyBurrow
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Profile" asp-action="Index" asp-route-id=@user?.Id>
                                <i class="fa fa-user">Profile</i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Chat" asp-action="List">
                                <i class="fa fa-comment">Chats</i>
                            </a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-light" role="button" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-users">Friends</i>
                            </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="" asp-controller="Request" asp-action="Friends"> Friends </a>
                                <a class="dropdown-item" asp-area="" asp-controller="Request" asp-action="Followers"> Followers </a>
                                <a class="dropdown-item" asp-area="" asp-controller="Request" asp-action="Following"> Following </a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Request" asp-action="SearchFriends">
                                <i class="fa fa-search"> Search</i>
                            </a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Profile" asp-action="Index" asp-route-id=@user?.Id>
                                    <img src="@Url.Content(imagePath)" class="avatar-small-size rounded-circle" />
                                    @User.Identity.Name
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                            @*
                                <li class="nav-item">

                                    <form asp-area="" asp-controller="account" asp-action="logout">
                                        <button type="submit" class="nav-link text-light btn btn-link" style="width:auto">
                                            Logout
                                        </button>
                                    </form>
                                </li>
                            *@
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="account" asp-action="register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="account" asp-action="login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-light bg-dark">
        <div class="container">
            &copy; 2020 - FoxyBurrow - Author: <a class="text-light" href="https://github.com/dimasindro">dimasiandro</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/timeOffset.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>